/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Test1;

import Test1.tasks.*;

public class App {

    public static void main(String[] args) {
        Test1.tasks.Task1 variable = new Task1();
        variable.execLists();
    }
}
